name: pass secret to reusable workflow
on:
  workflow_dispatch:
  
jobs:
  pass-secret-to-workflow:
    uses: Shresthaa-Adhikary/reusableworkflow/.github/workflows/passedsecret.yml@main
    secrets:
       token: ${{ secrets.ACCESS_TOKEN }}
