name: pass secret to reusable workflow
on:
  workflow_dispatch:
  
jobs:
  pass-secret-to-workflow:
    uses: reusableworkflow/.github/workflows/passedsecret.yml@main
    secrets:
       token: ${{ secrets.access_token }}
